### ISSUE TITLE
[bug] Watch fails to update if started when chromecast was idle

### ISSUE THREAD

**Issue by stephen304** [vishen/go-chromecast#70] opened 2020-07-17 22:55 UTC
To reproduce:
1. Ensure chromecast is idle - no app connected
2. Start go-chromecast watch -u xxxx
3. Play youtube on the chromecast

Result:
```
Idle (Backdrop), volume=1.00 muted=false
Idle (Backdrop), volume=1.00 muted=false
unable to update cast application: context deadline exceeded
```

Expected Result:
```
Idle (Backdrop), volume=1.00 muted=false
(probably something about starting the video here)
>> YouTube (PLAYING), title="The Hardest Challenge in any Zelda Game", artist="", time remaining=210s/813s, volume=1.00, muted=false
>> YouTube (PLAYING), title="The Hardest Challenge in any Zelda Game", artist="", time remaining=220s/813s, volume=1.00, muted=false
```

It seems to work fine if you start the watch command while something is playing.

**Comment by vishen** [comment] 2020-07-18 11:42
Thanks! I have noticed there is an issue like this but I haven't been able to reliably reproduce it. I'll look at fixing this!

**Comment by stephen304** [comment] 2020-07-18 13:03
Thanks a ton! This is pretty much the only breaking issue that prevents my castblock from being able to be left running I think. It seems to reproduce reliably for me - let me know if there's anything I can contribute debugging-wise.

**Comment by vishen** [comment] 2020-07-18 16:09
I have been able to reliably reproduce this, thanks so much for that! 

I think I can see the bug, we are trying to send to a channel that isn't ready (used for when playing media). I think the code is quite poorly designed around this since originally it was only designed to load and play media and has since had quite a bit of stuff added. I will push a quick hack fix for this, but now that I finally understand the issue it might be time to redesign some of the internals.

**Comment by vishen** [comment] 2020-07-18 16:43
I have pushed a fix for this, it seems to be working for me but please let me know if it doesn't work for you and I will look into it again!

**Comment by stephen304** [comment] 2020-07-18 17:54
Thanks! I'll let you know if I have any issues with it

**Comment by vishen** [comment] 2020-07-18 18:00
Awesome, thanks!

**Comment by vishen** [comment] 2020-09-15 21:31
@stephen304 I believe this should be fixed now? I am going to close this since I believe it is, but feel free to re-open if I am wrong :)

**Closed by vishen** 2020-09-15 21:31 UTC
